### ISSUE TITLE
Update times - gas price trouble

### ISSUE THREAD

**Issue by fakel** [hunterlong/fiatcontract#4]
Hi, recently the standard gas price used on the network has been increased and the updates on the contract are not going through with the 2 Gwei gas price.

Maybe an increase of the Gas price together to a increased update time interval could balance the contract.

**Comment by hunterlong** [comment]
I've increased the Gas Price, i'll work on making this dynamic sometime soon.

**Comment by hunterlong** [comment]
I've updated the server to fetch the current gas price before submitting the transaction. Should be good for long term use now.
